steps:
- name: maven:3-jdk-11
  entrypoint: mvn
  args: [ 'package','-Dmaven.test.skip=true' ]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
options: 
 logging: CLOUD_LOGGING_ONLY

